// components/CharNav.tsx
import { useRouter } from "next/router";
import { tw } from "twind";

export default function CharNav() {
  const router = useRouter();

  const alphabeticalSections: Record<
    string,
    Array<{ name: string; link: string }>
  > = {
    A: [
      {
        name: "about me",
        link: "/about",
      },
      {
        name: "anime",
        link: "/anime",
      },
    ],
    B: [
      {
        name: "bout me",
        link: "/about",
      },
      {
        name: "boob",
        link: "/anime",
      },
    ],
    C: [],
    D: [],
    E: [],
    F: [],
    G: [],
    H: [],
    I: [],
    J: [],
    K: [],
    L: [],
    M: [],
    N: [],
    O: [],
    P: [],
    Q: [],
    R: [],
    S: [],
    T: [],
    U: [],
    V: [],
    W: [],
    X: [],
    Y: [],
    Z: [],
  };

  const dropDownStringLength = (dropDownStrings: string[]) => {
    let length = 0;
    dropDownStrings.forEach((s, i) => {
      length = length + s.length;
      if (i < dropDownStrings.length - 1) {
        length = length + 2;
      }
    });
    return length;
  };

  return (
    <ul
      className={tw`
      w-full
      inline-flex
      justify-between`}
    >
      {Object.entries(alphabeticalSections).map((character, characterIndex) => {
        return (
          <li
            className={tw`flex 
            cursor-pointer
            p-2
            group`}
            key={characterIndex}
          >
            <h4
              className={tw`
              relative`}
            >
              <span>{character[0]}</span>
              <span
                className={tw`
                inline-flex
                divide-x-2
                divide-yellow-300
                absolute
                -left-1
                z-50
                transform-gpu
                rotate-90
                origin-bottom-left
                overflow-x-hidden
                whitespace-nowrap
                transition-width
                ease-linear
                duration-300
                w-0
                group-hover:w-[${
                  dropDownStringLength(character[1].flatMap((s) => s.name))
                }ch]`}
              >
                {character[1].map((section, sectionIndex) => {
                  let name = section.name;
                  if (sectionIndex < 1) {
                    name = name.substring(1);
                    return (
                      <a
                        className={tw`px-1`}
                        href={section.link}
                        key={`${characterIndex}-${sectionIndex}`}
                      >
                        {name}
                      </a>
                    );
                  } else {
                    return (
                      <a
                        className={tw`px-1`}
                        href={section.link}
                        key={`${characterIndex}-${sectionIndex}`}
                      >
                        {name}
                      </a>
                    );
                  }
                })}
              </span>
            </h4>
          </li>
        );
      })}
    </ul>
  );
}

// src/lib/components/CharNav.svelte
<script lang="ts">
	import { page } from '$app/stores';
	const alphabeticalSections: Record<string, Array<{ name: string; link: string }>> = {
		A: [
			{
				name: 'about me',
				link: '/about'
			},
		],
		B: [
			{
				name: 'bout me',
				link: '/about'
			},
		],
		C: [],
		D: [],
		E: [],
		F: [],
		G: [],
		H: [],
		I: [],
		J: [],
		K: [],
		L: [],
		M: [],
		N: [],
		O: [],
		P: [],
		Q: [],
		R: [],
		S: [],
		T: [],
		U: [],
		V: [],
		W: [],
		X: [],
		Y: [],
		Z: []
	};

	const dropDownStringLength = (dropDownStrings: string[]) => {
		let length = 0;
		dropDownStrings.forEach((s, i) => {
			length = length + s.length;
			if (i < dropDownStrings.length - 1) {
				length = length + 2;
			}
		});
		return length;
	};
</script>

<ul class="w-full inline-flex justify-between">
	{#each Object.entries(alphabeticalSections) as [character, sections], alphabeticalSectionIndex (alphabeticalSectionIndex)}
		<li class="flex p-2 group">
			<h4 class="relative">
				<span class="cursor-pointer">{character}</span>
				<span
					class="
                    inline-flex
                    divide-x-2
                    divide-yellow-300
                    absolute
                    -left-1
                    z-50
                    transform-gpu
                    rotate-90
                    origin-bottom-left
                    overflow-x-hidden
                    whitespace-nowrap
                    transition-width
                    ease-linear
                    duration-300
                    w-0
                    group-hover:w-[13ch]"
				>
					{#each sections as { name, link }, sectionIndex}
						{#if sectionIndex < 1}
							<a class="px-1 hover:text-yellow-300" href={link}>
								{name.substring(1)}
							</a>
						{:else}
							<a class="px-1 hover:text-yellow-300" href={link}>
								{name}
							</a>
						{/if}
					{/each}
				</span>
			</h4>
		</li>
	{/each}
</ul>
